### ISSUE TITLE
"Error: not opened" in nodefly node_modules "socket.io-client"

### ISSUE THREAD

**Issue by wwwy3y3** [NodeFly/NodeFly#18]
Hi!

I ran into this error

what does this mean?

```
Error: not opened
at WebSocket.send (/home/ubuntu/prod/node_modules/nodefly/node_modules/socket.io-client/node_modules/ws/lib/WebSocket.js:175:16)
at Transport.WS.send (/home/ubuntu/prod/node_modules/nodefly/node_modules/socket.io-client/lib/transports/websocket.js:107:22)
at Transport.packet (/home/ubuntu/prod/node_modules/nodefly/node_modules/socket.io-client/lib/transport.js:178:10)
at Transport.WS.payload (/home/ubuntu/prod/node_modules/nodefly/node_modules/socket.io-client/lib/transports/websocket.js:120:12)
at Socket.flushBuffer (/home/ubuntu/prod/node_modules/nodefly/node_modules/socket.io-client/lib/socket.js:327:20)
at Socket.setBuffer (/home/ubuntu/prod/node_modules/nodefly/node_modules/socket.io-client/lib/socket.js:314:14)
at Socket.onConnect (/home/ubuntu/prod/node_modules/nodefly/node_modules/socket.io-client/lib/socket.js:409:14)
at Transport.onConnect (/home/ubuntu/prod/node_modules/nodefly/node_modules/socket.io-client/lib/transport.js:139:17)
at Transport.onPacket (/home/ubuntu/prod/node_modules/nodefly/node_modules/socket.io-client/lib/transport.js:91:12)
at Transport.onData (/home/ubuntu/prod/node_modules/nodefly/node_modules/socket.io-client/lib/transport.js:69:16)
```

**Comment by themitchy** [comment]
Hey @wwwy3y3 ,

Which version of our agent are you using?

**Comment by wwwy3y3** [comment]
@themitchy 0.1.24

**Comment by themitchy** [comment]
Hey @wwwy3y3 ,

I've just pushed out 0.1.29 which should address the Socket.IO issue.  If the problem persists please run with NODEFLY_DEBUG=socket and send us the output before the crash.

**Comment by MaitreyaBuddha** [comment]
Hey @themitchy, what was your fix? I'm currently getting a similar stack from socket.io when I'm running a ton of connections.
