### ISSUE TITLE
Uncaught exceptions

### ISSUE THREAD

**Issue by dainis** [NodeFly/NodeFly#19]
Currently we have caught one uncaught exception and warning originating from nodefly

``` javascript
{
    "error": "Error: not opened",
    "message": "Error: not opened\    
      at WebSocket.send (/app/node_modules/nodefly/node_modules/socket.io-client/node_modules/ws/lib/WebSocket.js:175:16)\    
      at Transport.WS.send (/app/node_modules/nodefly/node_modules/socket.io-client/lib/transports/websocket.js:107:22)\    
      at Transport.packet (/app/node_modules/nodefly/node_modules/socket.io-client/lib/transport.js:178:10)\    
      at Socket.packet (/app/node_modules/nodefly/node_modules/socket.io-client/lib/socket.js:295:22)\    
      at SocketNamespace.packet (/app/node_modules/nodefly/node_modules/socket.io-client/lib/namespace.js:64:17)\    
      at SocketNamespace.emit (/app/node_modules/nodefly/node_modules/socket.io-client/lib/namespace.js:113:17)\    
      at SocketNamespace.<anonymous> (/app/node_modules/nodefly/lib/sockets.js:32:10)\    
      at SocketNamespace.EventEmitter.emit [as $emit] (/app/node_modules/nodefly/node_modules/socket.io-client/lib/events.js:165:15)\    
      at SocketNamespace.onPacket (/app/node_modules/nodefly/node_modules/socket.io-client/lib/namespace.js:152:14)\    
      at Socket.onPacket (/app/node_modules/nodefly/node_modules/socket.io-client/lib/socket.js:443:30)"
}
```

``` javascript
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. 
Use emitter.setMaxListeners() to increase limit.
Trace
    at CleartextStream.EventEmitter.addListener (events.js:175:15)
    at CleartextStream.exports.before.meths.forEach.obj.(anonymous function) [as on] (/app/node_modules/nodefly/lib/proxy.js:48:16)
    at httpSocketSetup (http.js:1731:10)
    at ClientRequest.onSocket (http.js:1617:5)
    at exports.callback.args.(anonymous function) (/app/node_modules/nodefly/lib/proxy.js:113:18)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
```

**Comment by themitchy** [comment]
Hey @dainis ,

Which version of our agent are you using?

**Comment by themitchy** [comment]
Hey @dainis,

I've just pushed out 0.1.29 which should address the Socket.IO issue.  If the problem persists please run with NODEFLY_DEBUG=socket and send us the output before the crash.

**Comment by rosskukulinski** [comment]
FYI @themitchy -- Our staging server just barfed with an uncaught exception, "not opened".  We're running nodefly 0.1.34, nodejs v0.6.19.  Error occurred in the middle of last night with _zero_ traffic or application activity.

We just added nodefly yesterday and the only reference in our source I can find of an error "not opened" is in the socket.io-client in Nodefly.

I'm updating our staging scripts to use NODEFLY_DEBUG=socket to try to isolate.

**Comment by flockonus** [comment]
+1 on Heroku, "stable" version

```
  "engines":{
    "node": "0.8.21",
    "npm": "1.2.12"
  },
```

```
2013-05-30T18:16:46.093787+00:00 app[web.1]: (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
2013-05-30T18:16:46.094468+00:00 app[web.1]:     at Transport.forEach.Transport.(anonymous function) [as update] (/app/node_modules/nodefly/lib/transport/uhura.js:35:8)
2013-05-30T18:16:46.094468+00:00 app[web.1]: Trace
2013-05-30T18:16:46.094468+00:00 app[web.1]:     at sendTiers (/app/node_modules/nodefly/lib/sender.js:122:14)
2013-05-30T18:16:46.094468+00:00 app[web.1]:     at Transport.EventEmitter.addListener (events.js:175:15)
2013-05-30T18:16:46.094468+00:00 app[web.1]:     at Transport.EventEmitter.once (events.js:196:8)
2013-05-30T18:16:46.094468+00:00 app[web.1]:     at Transport.SendEmitter.send (/app/node_modules/nodefly/node_modules/uhura/lib/send_emitter.js:115:7)
2013-05-30T18:16:46.094468+00:00 app[web.1]:     at Timer.exports.init.metricsBuffer (/app/node_modules/nodefly/lib/sender.js:72:4)
2013-05-30T18:16:46.094468+00:00 app[web.1]:     at tiersBuffer (/app/node_modules/nodefly/lib/sender.js:123:16)
2013-05-30T18:16:46.094468+00:00 app[web.1]:     at Timer.exports.setInterval.timer.ontimeout (timers.js:234:14)
2013-05-30T18:18:01.253269+00:00 app[web.1]: (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
2013-05-30T18:18:01.273648+00:00 app[web.1]:     at Transport.forEach.Transport.(anonymous function) [as update] (/app/node_modules/nodefly/lib/transport/uhura.js:35:8)
2013-05-30T18:18:01.273648+00:00 app[web.1]:     at Transport.EventEmitter.once (events.js:196:8)
2013-05-30T18:18:01.273648+00:00 app[web.1]:     at Transport.SendEmitter.send (/app/node_modules/nodefly/node_modules/uhura/lib/send_emitter.js:115:7)
2013-05-30T18:18:01.273648+00:00 app[web.1]: Trace
2013-05-30T18:18:01.273648+00:00 app[web.1]:     at Transport.EventEmitter.addListener (events.js:175:15)
2013-05-30T18:18:01.273648+00:00 app[web.1]:     at tiersBuffer (/app/node_modules/nodefly/lib/sender.js:123:16)
2013-05-30T18:18:01.273648+00:00 app[web.1]:     at sendTiers (/app/node_modules/nodefly/lib/sender.js:122:14)
2013-05-30T18:18:01.273648+00:00 app[web.1]:     at Timer.exports.setInterval.timer.ontimeout (timers.js:234:14)
2013-05-30T18:18:01.273648+00:00 app[web.1]:     at Array.forEach (native)
2013-05-30T18:18:01.273648+00:00 app[web.1]:     at Timer.exports.init.metricsBuffer (/app/node_modules/nodefly/lib/sender.js:72:4)
2013-05-30T18:19:15.502763+00:00 app[web.1]: (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
2013-05-30T18:19:15.503454+00:00 app[web.1]:     at Transport.SendEmitter.send (/app/node_modules/nodefly/node_modules/uhura/lib/send_emitter.js:115:7)
2013-05-30T18:19:15.503454+00:00 app[web.1]: Trace
2013-05-30T18:19:15.503454+00:00 app[web.1]:     at Transport.EventEmitter.once (events.js:196:8)
2013-05-30T18:19:15.503454+00:00 app[web.1]:     at Timer.exports.init.metricsBuffer (/app/node_modules/nodefly/lib/sender.js:72:4)
2013-05-30T18:19:15.503454+00:00 app[web.1]:     at Array.forEach (native)
2013-05-30T18:19:15.503454+00:00 app[web.1]:     at Transport.EventEmitter.addListener (events.js:175:15)
2013-05-30T18:19:15.503454+00:00 app[web.1]:     at Transport.forEach.Transport.(anonymous function) [as update] (/app/node_modules/nodefly/lib/transport/uhura.js:35:8)
2013-05-30T18:19:15.503454+00:00 app[web.1]:     at sendTiers (/app/node_modules/nodefly/lib/sender.js:122:14)
2013-05-30T18:19:15.503454+00:00 app[web.1]:     at tiersBuffer (/app/node_modules/nodefly/lib/sender.js:123:16)
2013-05-30T18:19:15.503454+00:00 app[web.1]:     at Timer.exports.setInterval.timer.ontimeout (timers.js:234:14)
2013-05-30T18:20:15.311476+00:00 app[web.1]:  /!\ GET /api/web_questions /!\
2013-05-30T18:20:15.311476+00:00 app[web.1]: 
2013-05-30T18:20:15.319253+00:00 app[web.1]: 200|GET|/api/web_questions?num_questions=10|7 ms
2013-05-30T18:20:15.333384+00:00 heroku[router]: at=info method=GET path=/api/web_questions?num_questions=10 host=persomm-api.herokuapp.com fwd="96.49.142.70" dyno=web.1 connect=13ms service=24ms status=200 bytes=14727
2013-05-30T18:20:15.752616+00:00 app[web.1]: (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
2013-05-30T18:20:15.753410+00:00 app[web.1]:     at Transport.EventEmitter.once (events.js:196:8)
2013-05-30T18:20:15.753410+00:00 app[web.1]:     at Transport.EventEmitter.addListener (events.js:175:15)
2013-05-30T18:20:15.753410+00:00 app[web.1]:     at Array.forEach (native)
2013-05-30T18:20:15.753410+00:00 app[web.1]: Trace
2013-05-30T18:20:15.753410+00:00 app[web.1]:     at Transport.SendEmitter.send (/app/node_modules/nodefly/node_modules/uhura/lib/send_emitter.js:115:7)
2013-05-30T18:20:15.753410+00:00 app[web.1]:     at Timer.exports.init.metricsBuffer (/app/node_modules/nodefly/lib/sender.js:72:4)
2013-05-30T18:20:15.753410+00:00 app[web.1]:     at tiersBuffer (/app/node_modules/nodefly/lib/sender.js:123:16)
2013-05-30T18:20:15.753410+00:00 app[web.1]:     at Transport.forEach.Transport.(anonymous function) [as update] (/app/node_modules/nodefly/lib/transport/uhura.js:35:8)
2013-05-30T18:20:15.753410+00:00 app[web.1]:     at Timer.exports.setInterval.timer.ontimeout (timers.js:234:14)
2013-05-30T18:20:15.753410+00:00 app[web.1]:     at sendTiers (/app/node_modules/nodefly/lib/sender.js:122:14)
```

**Comment by themitchy** [comment]
We've switched off of websockets and Socket.io in the latest version.  Please try the latest stable version of nodefly (0.1.42).

**Comment by Prinzhorn** [comment]
Just had the same logs entries on Heroku after I added nodefly yesterday. package.json says `"nodefly": "stable"` so I guess it's using 0.1.42
