### ISSUE TITLE
Error on Heroku deploy

### ISSUE THREAD

**Issue by jswartwood** [NodeFly/NodeFly#22]
I'm getting this when trying  to deploy to Heroku (on Node v0.10).

```
   make: Entering directory `/tmp/build_2xeoa83ucdwv4/node_modules/nodefly/node_modules/memwatch/build'
   npm http 200 https://registry.npmjs.org/options/-/options-0.0.3.tgz
     CXX(target) Release/obj.target/memwatch/src/heapdiff.o

   > ws@0.4.25 install /tmp/build_2xeoa83ucdwv4/node_modules/nodefly/node_modules/socket.io-client/node_modules/ws
   > (node-gyp rebuild 2> builderror.log) || (exit 0)

   make: Entering directory `/tmp/build_2xeoa83ucdwv4/node_modules/nodefly/node_modules/socket.io-client/node_modules/ws/build'
     CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
     SOLINK_MODULE(target) Release/obj.target/bufferutil.node
     SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
     COPY Release/bufferutil.node
     CXX(target) Release/obj.target/validation/src/validation.o
     CXX(target) Release/obj.target/memwatch/src/init.o
     SOLINK_MODULE(target) Release/obj.target/validation.node
     SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
     COPY Release/validation.node
   make: Leaving directory `/tmp/build_2xeoa83ucdwv4/node_modules/nodefly/node_modules/socket.io-client/node_modules/ws/build'
     CXX(target) Release/obj.target/memwatch/src/memwatch.o
   ../src/memwatch.cc: In function 'void memwatch::after_gc(v8::GCType, v8::GCCallbackFlags)':
   ../src/memwatch.cc:227: error: invalid conversion from 'void (*)(uv_work_t*)' to 'void (*)(uv_work_t*, int)'
   ../src/memwatch.cc:227: error:   initializing argument 4 of 'int uv_queue_work(uv_loop_t*, uv_work_t*, void (*)(uv_work_t*), void (*)(uv_work_t*, int))'
   make: *** [Release/obj.target/memwatch/src/memwatch.o] Error 1
   make: Leaving directory `/tmp/build_2xeoa83ucdwv4/node_modules/nodefly/node_modules/memwatch/build'
   gyp ERR! build error
   gyp ERR! stack Error: `make` failed with exit code: 2
   gyp ERR! stack     at ChildProcess.onExit (/tmp/node-npm-sD6a/node_modules/node-gyp/lib/build.js:255:23)
   gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
   gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:754:12)
   gyp ERR! System Linux 2.6.32-350-ec2
   gyp ERR! command "node" "/tmp/node-npm-sD6a/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
   gyp ERR! cwd /tmp/build_2xeoa83ucdwv4/node_modules/nodefly/node_modules/memwatch
   gyp ERR! node -v v0.10.0
   gyp ERR! node-gyp -v v0.8.4
   gyp ERR! not ok
   npm WARN optional dep failed, continuing memwatch@0.1.5
```

Removing NodeFly as a dependency solves this issue.

**Comment by jswartwood** [comment]
Also, from the look of the error ("...optional dep failed..."), it looks like it might be able to pass despite not functioning 100%. However, later I see this in the deploy log...

```
   nodefly@0.1.31 node_modules/nodefly
   ├── async@0.1.22
   ├── restler@2.0.1
   ├── measured@0.1.3
   ├── underscore@1.4.4
   ├── nodefly-gcinfo2@0.0.15
   ├── socket.io-client@0.9.11 (xmlhttprequest@1.4.2, uglify-js@1.2.5, ws@0.4.25, active-x-obfuscator@0.0.1)
   └── timekit@0.1.8 (bindings@1.1.0)
   npm ERR! Error: spawn ENOENT
   npm ERR!     at errnoException (child_process.js:945:11)
   npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:736:34)
   npm ERR! If you need help, you may report this log at:
   npm ERR!     <http://github.com/isaacs/npm/issues>
   npm ERR! or email it to:
   npm ERR!     <npm-@googlegroups.com>

   npm ERR! System Linux 2.6.32-350-ec2
   npm ERR! command "/tmp/node-node-aF1G/bin/node" "/tmp/node-npm-sD6a/cli.js" "rebuild"
   npm ERR! cwd /tmp/build_2xeoa83ucdwv4
   npm ERR! node -v v0.10.0
   npm ERR! npm -v 1.2.12
   npm ERR! syscall spawn
   npm ERR! code ENOENT
   npm ERR! errno ENOENT
   npm ERR!
   npm ERR! Additional logging details can be found in:
   npm ERR!     /tmp/build_2xeoa83ucdwv4/npm-debug.log
   npm ERR! not ok code 0
 !     Failed to rebuild dependencies with npm
 !     Heroku push rejected, failed to compile Node.js app
```

**Comment by DaveYVR** [comment]
Hi Jacob,

Thanks for reaching out to us. We're still looking into it further, but we
wanted to let you know we received this email and were working on it.

Cheers,

Dave

**Comment by damonmorgan** [comment]
+1

**Comment by faridnsh** [comment]
`nodefly` installs fine on node v0.8.22 but I get that error on node v0.10.1

**Comment by AndrewMartens** [comment]
nodefly@0.1.31 did exhibit this issue, due to using a version of memwatch that was incompatible with node v0.10.0.  That has since been removed from nodefly's dependencies in both 0.1.32 and 0.1.34.

If you are having trouble with this issue, please try the latest version of nodefly.
