### ISSUE TITLE
Launch error  with node.js

### ISSUE THREAD

**Issue by willrnch** [NodeFly/NodeFly#26]
I have the following error at launch (but reporting works well):

```
2013-04-05T09:11:12+00:00 app[web.2]: nodefly error: [TypeError: Cannot read property '__required__' of undefined] TypeError: Cannot read property '__required__' of undefined
2013-04-05T09:11:12+00:00 app[web.2]:     at Nodefly.profile.socket.sockets.init.agent (/app/node_modules/nodefly/lib/nodefly.js:96:10)
2013-04-05T09:11:12+00:00 app[web.2]:     at Module.exports.after.meths.forEach.obj.(anonymous function) [as require] (/app/node_modules/nodefly/lib/proxy.js:70:10)
2013-04-05T09:11:12+00:00 app[web.2]:     at require (module.js:378:17)
2013-04-05T09:11:12+00:00 app[web.2]:     at Object.<anonymous> (/app/web.js:10:1)
2013-04-05T09:11:12+00:00 app[web.2]:     at Module._compile (module.js:449:26)
2013-04-05T09:11:12+00:00 app[web.2]:     at Object.Module._extensions..js (module.js:467:10)
2013-04-05T09:11:12+00:00 app[web.2]:     at Module.load (module.js:356:32)
2013-04-05T09:11:12+00:00 app[web.2]:     at Function.Module._load (module.js:312:12)
2013-04-05T09:11:12+00:00 app[web.2]:     at Module.runMain (module.js:492:10)
2013-04-05T09:11:12+00:00 app[web.2]:     at process.startup.processNextTick.process._tickCallback (node.js:244:9)
```

**Comment by sprice** [comment]
I'm having the same error, also on Heroku. Node 0.10.4, nodefly@0.1.37. My app is still running.

I also notice that the Memory Management page in NodeFly has no data. Not sure if it's related.
