### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by ececilla** [NodeFly/NodeFly#32]
Hi guys, 

i got this uncaugth exception when starting my server. Don't want nodefly to crash the server if cannot connect to the backend. Is it a bug or i should catch the exception myself?

Some info regarding the environment:
Openshift paas
Node version 0.8.9
Nodefly agent version 0.1.40 (latest stable as recommended)

{
app-root/runtime/repo/node_modules/nodefly/node_modules/socket.io-client/node_modules/ws/lib/WebSocket.js:175
    else throw new Error('not opened');
               ^
Error: not opened
    at WebSocket.send (app-root/runtime/repo/node_modules/nodefly/node_modules/socket.io-client/node_modules/ws/lib/WebSocket.js:175:16)
    at Transport.WS.send (app-root/runtime/repo/node_modules/nodefly/node_modules/socket.io-client/lib/transports/websocket.js:107:22)
    at Transport.packet (app-root/runtime/repo/node_modules/nodefly/node_modules/socket.io-client/lib/transport.js:178:10)
    at Socket.packet (app-root/runtime/repo/node_modules/nodefly/node_modules/socket.io-client/lib/socket.js:295:22)
    at SocketNamespace.packet (app-root/runtime/repo/node_modules/nodefly/node_modules/socket.io-client/lib/namespace.js:64:17)
    at SocketNamespace.emit (app-root/runtime/repo/node_modules/nodefly/node_modules/socket.io-client/lib/namespace.js:113:17)
    at SocketNamespace.<anonymous> (app-root/runtime/repo/node_modules/nodefly/lib/sockets.js:40:10)
    at SocketNamespace.EventEmitter.emit [as $emit](app-root/runtime/repo/node_modules/nodefly/node_modules/socket.io-client/lib/events.js:165:15)
    at SocketNamespace.onPacket (app-root/runtime/repo/node_modules/nodefly/node_modules/socket.io-client/lib/namespace.js:152:14)
    at Socket.onPacket (app-root/runtime/repo/node_modules/nodefly/node_modules/socket.io-client/lib/socket.js:443:30)
npm info app@0.0.9-1 Failed to exec start script
npm ERR! app@0.0.9-1 start: `node index.js`
...
}

**Comment by DaveYVR** [comment]
Thanks for reaching out. We're now at 0.1.41 - please update and let us know if you have any further issues.
