### ISSUE TITLE
nodefly error: [TypeError: Object.keys called on non-object]

### ISSUE THREAD

**Issue by rudolf** [NodeFly/NodeFly#37]
I keep getting this error using strong-agent@0.2.12

nodefly error: [TypeError: Object.keys called on non-object] TypeError: Object.keys called on non-object
  at Function.keys (native)
  at sanitize (/app/node_modules/strong-agent/lib/probes/mongodb.js:77:9)
  at filterValue (/app/node_modules/strong-agent/lib/probes/mongodb.js:73:11)
  at /app/node_modules/strong-agent/lib/probes/mongodb.js:78:17
  at Array.forEach (native)
  at sanitize (/app/node_modules/strong-agent/lib/probes/mongodb.js:77:21)
  at filterValue (/app/node_modules/strong-agent/lib/probes/mongodb.js:73:11)
  at /app/node_modules/strong-agent/lib/probes/mongodb.js:78:17
  at Array.forEach (native)
  at sanitize (/app/node_modules/strong-agent/lib/probes/mongodb.js:77:21)
  at /app/node_modules/strong-agent/lib/probes/mongodb.js:92:27
  at Db.newFunc [as _executeQueryCommand](/app/node_modules/strong-agent/lib/proxy.js:24:10)
  at Cursor.nextObject (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/cursor.js:674:13)
  at Cursor.toArray (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/cursor.js:154:10)
  at /app/node_modules/mongoose/lib/query.js:1674:12
  at Collection.find (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection.js:872:5)
  at NativeCollection.(anonymous function) [as find](/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:129:21)
  at Query.execFind (/app/node_modules/mongoose/lib/query.js:1672:20)
  at Query.find (/app/node_modules/mongoose/lib/query.js:204:15)
  at Query.exec (/app/node_modules/mongoose/lib/query.js:171:16)

**Comment by Qard** [comment]
That was fixed in 0.2.13. Try updating. Also, if your agent is locked to a specific version in package.json, please change it to "latest".

**Comment by rudolf** [comment]
Thanks, I'm on "stable" which is probably the same as "latest"? Our latest deployment with 0.2.14 fixed this issue. 

With the amount of issues we've had related to strong-agent, I'm becoming more and more weary to have it auto update. With the risk of things breaking after any release, I'm thinking of only periodically updating strong-agent in order to thoroughly test it.

**Comment by Qard** [comment]
Sorry you've had a bad experience with it.

The "stable" tag is not quite the same as "latest" in npm. The "latest" tag is an autotag, so it will always point to the highest version number, while the "stable" tag points to the latest version we've manually flagged as stable. With our recent acquisition, we are focusing even more on making sure every release is stable, so the need for an explicit tag for that is disappearing.

Also, the package will only update when you tell it to. There's no auto-updating. You have to explicitly npm update or npm install to fetch the current "latest" tagged version.

**Comment by rudolf** [comment]
Thanks for clarifying "latest" vs "stable". 

I'm aware that there's no such thing as "auto-updates" (they need to be initiated), but specifying latest as a version "automatically" updates strong-agent when it might not be your intent.
